# join our discord: https://discord.gg/aEK8KzB #
name: CustomMobDropsPMMP
main: ProxyTechDevs\CustomMobDrops\Main
version: 1.0.0
api: [3.0.0]
author: ProxyTechDevs
# join our discord: https://discord.gg/aEK8KzB #
